name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: prettier:all 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint:all 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspace @klu-food/shared run
